### ISSUE TITLE
[BUG]: Middle-clicking on tabs to close them does not work if tabs overflow offscreen.

### ISSUE THREAD

**Issue by Kangie** [Zettlr/Zettlr#1225]
## Description
Using middle-click to close tabs does not work if there are more tabs than can be displayed on the screen. 

## Reproducing
Open a number of files in Zettlr (6+ in 1080p) to cause the tabs to begin to overflow 

## Expected behaviour
Middle click should always close tabs, the mousewheel can already be used to scroll the tabs, so I don't see a need for a middle-click action that's inconsistent.

## Platform
 - OS and version: Win10 (20.04)
 - Zettlr Version: 1.7.5
 - Screen Resolution: 1920x1080

## Additional information
Video of this bug in action: [video.zip](https://github.com/Zettlr/Zettlr/files/5160373/video.zip)

**Comment by nathanlesage** [comment]
> Video of this bug in action: video.zip

Please do not upload ZIP files. Use any preferred hoster so that no downloads are required for this, please.

Furthermore: Does the console (Develop menu -> Toggle Developer tools -> Console tab) show some error or something? Might be related to #801 (pinging @Zverik )

**Comment by Kangie** [comment]
Hi @nathanlesage 

Apologies, [here's](https://streamable.com/bn5tu0) the video hosted on streamable. 

I can't see anything in the log when this middle-click behaviour occurs, but do see file close actions when the click registers.

**Comment by nathanlesage** [comment]
Aaaaaah, the video explains it! The middle click on Windows triggers a scroll action (which I'm afraid we can't really circumvent, as not all mouses have a horizontal-scroll-scroll wheel)

**Comment by Kangie** [comment]
VSCode makes this work by providing `Ctrl + PgUp` and `Ctrl + PgDn` controls to navigate between tabs when a scrollwheel isn't available. 

> I'm afraid we can't really circumvent, as not all mouses have a horizontal-scroll-scroll wheel

You can scroll through the tabs in Zettlr using a 'regular' mousewheel (scroll up & scroll down). If you *have* a mousewheel, midde-click behaviour should close tabs, and if you don't have a mousewheel in 2020... I don't know!

**Comment by nathanlesage** [comment]
Yeah, basically it would mean to disable the comfortable scrolling, but I'm in favor of that approach. Unfortunately, I can't test it, but I just committed something, so maybe it works now (but someone with a windows computer might want to test it)

**Comment by Kangie** [comment]
Just checked on the develop branch. Not working on windows. :(

**Comment by Kangie** [comment]
Huh. Seems to work in 1.8.0 alpha on windows. I don't know why it didn't when I tested.

**Comment by nathanlesage** [comment]
Hehehehe, I like it if certain problems solve themselves :D

So, can we close this issue? 🧐

**Comment by Kangie** [comment]
Ugh, no. I was silly yesterday and didn't have quite enough tabs open to trigger this behaviour. It's not fixed and I got very excited over nothing. :'(
