### ISSUE TITLE
Sometimes when you hover over the keyword count (e.g. #5), it lists the keywords; sometimes it doesn't.

### ISSUE THREAD

**Issue by Bestulo** [Zettlr/Zettlr#1397]
## Description
On the left bar, where the list of texts is, beside the ID, there is a little keyword counter with a hashtag number. (`#3` or `#11`, for example), and when I hover it sometimes, it gives a comma-separated list of keywords. Sometimes, though, hovering it with my mouse does nothing!

## Reproducing
I don't know if I'm doing something wrong, but I think it's a Zettlr bug. I wish I knew how to reproduce it, but it just happens spontaneously while I'm writing and checking the results of what I do.

## Expected behaviour
![image](https://user-images.githubusercontent.com/23301025/97955485-a79a7580-1d7c-11eb-9e4f-45e865c3b29c.png)

I think hovering over this little hashtag number should consistently give me a list of tags used in the text. It's a pretty useful feature that I miss whenever I can't make it work.

## Platform
 - OS and version: Windows 10
 - Zettlr Version: 1.7.5

**Comment by Bestulo** [comment]
I've tracked the problem. If it has an ID, it gets bugged. If it doesn't have an ID, it's okay.

Without an ID: https://i.imgur.com/r7CkyXL.gifv
With an ID: https://i.imgur.com/rlBDTVQ.gifv

**Comment by nathanlesage** [comment]
> I've tracked the problem. If it has an ID, it gets bugged. If it doesn't have an ID, it's okay.

That narrows the problem down very nicely, thanks! However, I just tried it out and cannot reproduce this. This might have several reasons:

- Maybe it's already fixed in the 1.8-branch – would you mind giving it a little test?
- Maybe I didn't try it too long for the bug to appear (but in the codebase it looks perfectly fine)

A third reason might be trivial. There is a little element that also overlays the tag list, which prevents the tooltip from being shown:

![image](https://user-images.githubusercontent.com/17251683/97957827-425e7880-1dac-11eb-885f-407fd42ba982.png)

So, very stupid question, but: Would you mind attempting to enlargening the file list until approximately the space taken by above-shown element is free next to the tag indicator? If it then consistently works, this is the real reason.

**Comment by Bestulo** [comment]
About testing 1.8, I don't know how. The site downloads a 1.75 exe, and there's no Release tab on the GH repo. I'm not sure I'm savvy enough to build the source myself.

About my current version, I tested and yes, that's it. The shadowy thing covers the tag and the pointer can't reach it.

**Comment by Bestulo** [comment]
Well, can't say I didn't try!

```js
⠇ Packaging Application
An unhandled rejection has occurred inside Forge:
Error: rcedit.exe failed with exit code 1. Unable to load file: "/tmp/electron-packager/win32-x64/Zettlr-win32-x64/Zettlr.exe"
    at ChildProcess.<anonymous> (/mnt/c/Users/sn/projects/Zettlr/node_modules/rcedit/lib/rcedit.js:71:16)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Socket.<anonymous> (internal/child_process.js:438:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:672:12)

Electron Forge was terminated. Location:
{}
error Command failed with exit code 1.
```

**Comment by nathanlesage** [comment]
> The site downloads a 1.75 exe, and there's no Release tab on the GH repo.

The site always gives you stables, not betas. With regard to the releases: https://github.com/Zettlr/Zettlr/releases

**Comment by Bestulo** [comment]
Ok I installed beta and the problem persists in beta :) And an additional problem appears in the same area.

1. If I drag the little bar, where the <--> sign appears, the **selection** priority falls on the file below. So you instead drag the file.
2. Once you unclick to drop the file, it turns out both were selected, file and sidebar border, and since only the file perceived the unclick, the border thinks it's still clicked and keeps moving.

![6l4gwQveL4](https://user-images.githubusercontent.com/23301025/98068393-4d5bec00-1e32-11eb-814f-2714997ce4f1.gif)

Ironically, the shadow, while it still allows you to click the item below, doesn't allow the keyword list to be triggered on hover.

![0m7oqBkh5M](https://user-images.githubusercontent.com/23301025/98068600-dbd06d80-1e32-11eb-947a-94ec1bd27e8e.gif)

**Comment by nathanlesage** [comment]
Closing, seeing this as fixed, I'm pretty sure this works on the 1.8.x series.
