### ISSUE TITLE
Slow tab switching

### ISSUE THREAD

**Issue by tobiasvandriessel** [Zettlr/Zettlr#1524]
## Description

Switching to and from a tab of a large file is very slow. The file contains possibly long lines, with tasks, headings, bold text, and inline latex.

## Reproducing

1) Create a new file
2) Put the contents in from the collapsed section below, and copy/paste it until you reach around 650 lines.
3) Switch to any other open tab. Now you should already see a loading time of a few seconds. For the other tab, I use a small file of 40 lines or so.
4) Switch back to the just created file tab, loading time should now be almost doubled.

For me, step 3 takes 5 seconds and step 4 takes 10 seconds.

<details> 
<summary>Big file contents that should be copy/pasted often</summary>
#### Week 1
_Tasks for this week_: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in nulla et sem sagittis molestie. Suspendisse a ultrices erat. Praesent magna tellus, malesuada id enim vulputate, eleifend finibus elit. Nam vitae interdum mauris, vitae vulputate ex. Nullam congue leo eu nulla accumsan bibendum. Quisque quis risus vel mi eleifend feugiat. Integer ornare hendrerit metus, eu scelerisque ante viverra id. Sed vel sapien a enim rutrum imperdiet. Fusce pellentesque varius ipsum, at dictum mauris euismod molestie.

**Day 1**
- [x] Task 1: Ensure that $b$ , $o$ and $c$ are solved.
- [ ] Task 2: Aliquam in consequat eros. Nulla facilisi. Phasellus eu odio nisl. Sed posuere s
- [x] Task 3: Vestibulum ante nisl, gravida et nisi aliquet, varius mollis risus. Maecenas molestie quam urna, et congue ipsum dignissim vitae. Quisque quam odio, placerat semper porttitor nec, molestie at purus. Nam tristique tristique pellentesque. Praesent tristique elementum ante, vel commodo ipsum. Sed consectetur neque nec lorem elementu
- [x] Task 4 Sed euismod eu diam a ullamcorper. Donec feugiat quis erat quis placerat. Etiam porttitor est in
- [ ] Task 5: Nullam dignissim, nibh vel dictum laoreet, ex tellus facilisis enim, quis lobortis neque arcu nec nisi. Maecenas nec nunc tempor, convallis felis quis, pretium est. Etiam sagittis arcu vel consectetur condimentum. Proin varius, libero vitae efficitur lacinia, nisi diam porttitor tortor, at feugiat nulla lacus e
_How did it go_:  eros. Nulla facilisi. Phasellus eu odio nisl. Sed posuere sem et nulla dictum, a finibus velit elementum. Fusce at pharetra nibh. Mauris tempus, nequ
_What can be improved_
_How many hours_:  quis lobortis neque arcu nec nisi. Maecenas ne
_blabla_: 
</details>

## Expected behaviour

In my expectation, switching a tab should not reload the file or whatever is happening under the hood. I can't imagine that switching to a different tab in a browser would take that much time, but I don't know if that's a fair reference point (I would say so, as it is based on chromium). However, I don't know if my expectations are correct. 

## Platform
 - OS and version: 
      Operating System: Debian GNU/Linux bullseye/sid
      Kernel: Linux 5.9.0-4-amd64
      Architecture: x86-64
 - Zettlr Version: 1.8.3 , however I've experienced this the past 1 or 2 months or so with various versions (before that it was not that big, as it is a diary)

**Comment by tobiasvandriessel** [comment]
I'm not sure if this is related, but I can't seem to delete the file from the file list in the sidebar at the left side, nor can I delete a newly created file (without any contents) in the same way.

**Comment by nathanlesage** [comment]
Well, switching tabs is a little bit slow, but I'm always trying to make it faster and faster. The file is never reloaded, and the text markers (the rendered elements, such as task lists, etc.) are never re-rendered as well. It seems to me you are experiencing a different problem, so I would like to ask you to see what seems to be happening, which means: Have a look both at the dev console and into the logs if there is something happening. If there are warnings or errors, this will help me, but right now there's no useful information for me to begin digging, unfortunately.

**Comment by tobiasvandriessel** [comment]
Hi Nathan,

Thanks for your quick response. 

Alright, thanks for the pointers for where to look. The log just shows 'Trying to run command through Application: set-active-file', so that seems alright. As for the dev console, I get some interesting results, with which I can not do anything more, but I hope you can. 

So first I record the performance while switching:
![scrsht0](https://user-images.githubusercontent.com/8767864/102349479-ab3c3180-3fa3-11eb-8183-4a96c9e07080.png)

We can see that in either of the three spikes, the function ft is the culprit and takes up a big chunk with its child calls. 
This function is the getContextBefore function at codemirror.js:1127

<details> 
<summary> getContextBefore function details </summary>
  function getContextBefore(cm, n, precise) {
    var doc = cm.doc, display = cm.display;
    if (!doc.mode.startState) { return new Context(doc, true, n) }
    var start = findStartLine(cm, n, precise);
    var saved = start > doc.first && getLine(doc, start - 1).stateAfter;
    var context = saved ? Context.fromSaved(doc, saved, start) : new Context(doc, startState(doc.mode), start);

    doc.iter(start, n, function (line) {
      processLine(cm, line.text, context);
      var pos = context.line;
      line.stateAfter = pos == n - 1 || pos % 5 == 0 || pos >= display.viewFrom && pos < display.viewTo ? context.save() : null;
      context.nextLine();
    });
    if (precise) { doc.modeFrontier = context.line; }
    return context
  }
</details>


![scrsht1](https://user-images.githubusercontent.com/8767864/102349475-aaa39b00-3fa3-11eb-82eb-4d32c4986298.png)

Now we see that the child function r (getContextBefore) is the real culprit, as it takes 71.2% of the time spent of the ~3 seconds. It tries to do some regular expression matching, and is located at multiplex.js:18 : 

<details> <summary> getContextBefore </summary>
function indexOf(string, pattern, from, returnEnd) {
    if (typeof pattern == "string") {
      var found = string.indexOf(pattern, from);
      return returnEnd && found > -1 ? found + pattern.length : found;
    }
    var m = pattern.exec(from ? string.slice(from) : string);
    return m ? m.index + from + (returnEnd ? m[0].length : 0) : -1;
  }
</details>

I'm not very familiar with Javascript, but I hope these images gave you a basic idea of what's going on.

Btw, when you open a file for the first time and scroll through it, it's intended behaviour that tasks (and perhaps also other things) are rendered on-the-fly, right?

Cheers for the hard work and let me know if there's anything else I can do to clarify anything.

**Comment by nathanlesage** [comment]
Thank you! This is indeed something better. I have two additional questions and also some answers:

1. Do you have several documents of a different type (e.g. switching between tex and markdown)? If so that explains the long duration of the setOption-task, as Codemirror has to run the whole file again through the parser, which takes a lot of time
2. What config option did you set (the last spike with the "configChange" call)?

Now to the answers:

1. That the elements render on the fly is the result of one performance optimisation: Elements are now not rendered immediately, but on two conditions: First, the line has to be in the viewport, and second, there must be an empty spot in the event loop (rendering since 1.8.1 or 1.8.2 is deferred to times where there is no other operation running)
2. What happens if you switch files:
    1. The wanted file is being set to active in the main process
    2. The main process tells the renderer to switch to said file
    3. The renderer looks up if it already has the file. If not, it retrieves the file's contents from main first
    4. Then it sets the editor mode if there is a change of document formats (md->tex and vice versa)
    5. Afterwards, it swaps the document
    6. The document swap means that CodeMirror will internally switch the editor contents to the next document, and then runs a full highlighter on it again. See for that point three below:
3. One big problem, especially for _long lines- (!), that I have unearthed recently is that the multiplex mode takes exponentially longer to finish its operations the longer the line gets. I am already on to it and will fix that in a future version.

**Comment by tobiasvandriessel** [comment]
Great to hear, thanks for your answers. So basically I would need to use shorter lines to speed up the switching?

As to your questions:
1. No, in my workspace I have only markdown files. 
2. I did not change any config option, so I don't know why configChange is being called...

However, one thing that might have an influence is the fact that I use the file sync program by Synology to sync my files with a remote NAS. I don't know how it would make a difference, but I can imagine this does matter somehow.

**Comment by nathanlesage** [comment]
Hm, curious, this almost sounds as if there's a small bug somewhere. Please keep your eyes open in case you notice any reproducible thing!

**Comment by tobiasvandriessel** [comment]
Alright, will do!

**Comment by mattj23** [comment]
Looking at it, this is the same issue as #1591 and #1523.  Those regular expression checks (scss, scala, sql, etc) showing up and taking ~48ms each are part of the multiplexer mode's brute force checking in the `token` method.  When I was trying to fix the long line issue I noticed that the `indexOf` method @nathanlesage identified as the culprit in #1523 seems to run heavily when a tab becomes active.

Pull request #1594 in theory should fix this as well.

**Comment by tobiasvandriessel** [comment]
Alright, I'll keep an eye out for the update and will get back to you on whether it did.

**Comment by nathanlesage** [comment]
Even with PR #1594 in place tab switching is still not perfectly good in my opinion. But I assume at a certain point we'll be hitting the limits of CodeMirror 5.

However, we have two additional performance sinks that add a lot of lag:

`signalFileAutoComplete` which fires on switching tabs and populates the file autocompletion database (the thing you get when typing `[[`). Possibly we could move that to an idle caller …?

The second thing is that the configuration is getting updated often in the renderer, because the renderer doesn't check which options have been updated. However, we need a better implementation of the setters in the config either way so that we can actually check what's happening.

**Comment by tobiasvandriessel** [comment]
Today I have tested the difference between 1.8.3 and 1.8.6 on my laptop, as I don't notice any lag on my desktop anymore on 1.8.6 (unless I pay close attention). 
On my laptop I have a 1 second delay when I switch tabs (on big files at least), but that is very usable, so you can consider this issue closed if it were up to me.
You have an additional Patreon member, thanks for the hard work!
