### ISSUE TITLE
Auto top-and-back scrolling in typing

### ISSUE THREAD

**Issue by dukebarman** [Zettlr/Zettlr#1555]
## Description
When I start to type a text at last line Zettlr starts to scroll top and back.

## Reproducing
I have a file with one two lines header and text more than one window (file for testing in attachment). And start to type at the last line.

## Expected behaviour

Don't auto random scroll in typing.

![zettlr_jumping](https://user-images.githubusercontent.com/1186777/102994638-7fcfbe80-4530-11eb-81ee-169f2b8fe815.gif)

## Platform

 - OS and version: Windows 10
 - Zettlr Version: 1.8.3

## Additional information

[Markdown file with the auto-generated random text for testing](https://github.com/Zettlr/Zettlr/files/5734998/zettlr_scroll_test.zip)

**Comment by nathanlesage** [comment]
I have no idea where this came from, but I noticed it myself. Mitigation for now: Just use the typewriter mode. Not the best mitigation, I know, but it works for now ¯\\\_(ツ)\_/¯

**Comment by dukebarman** [comment]
I've added a few empty lines at the end of file :)

**Comment by mattwien** [comment]
I have even the additional situation, that when I'm not writing in the last line - to avoid the behavior, Zettler regularely scrolls down a few lines - which is not so nice when you want to edit a longer text. Might be connected to this one. Will also try the typewriter mode, as it seems to be a good workaround.

**Comment by ivoseverins** [comment]
> I have even the additional situation, that when I'm not writing in the last line - to avoid the behavior, Zettler regularely scrolls down a few lines - which is not so nice when you want to edit a longer text. Might be connected to this one. Will also try the typewriter mode, as it seems to be a good workaround.

I have this as well. It seems to occur when the document is saved (either manually or automatically).

**Comment by cyannuremagik** [comment]
> > I have even the additional situation, that when I'm not writing in the last line - to avoid the behavior, Zettler regularely scrolls down a few lines - which is not so nice when you want to edit a longer text. Might be connected to this one. Will also try the typewriter mode, as it seems to be a good workaround.
> 
> I have this as well. It seems to occur when the document is saved (either manually or automatically).

I confirm this. I had the issue and was trying to figure out what was causing it.
It was easy to reproduce:

1. Open a note (new or not) that is long enough so scrolling is enabled 
2. Do any action on the document to trigger an autosave (write, delete, add space, change formatting)
3. Wait for autosave to happen (shown by removal of * in the tab name). It does not matter whether you scroll or stay still during that period. 
4. Note automatically scrolls towards the top, by a random number of lines. For me it does not go all the way to the top. 

There is maybe 1 second between the removal of the * and the autoscrolling. 

It also did that in Typewriter mode on 1.8.7, 
It does not matter if you have extra empty line at the document (did not for me at least)

So it seems to be related or caused by something that happens right after the autosave (**refresh**?)

**Comment by ploum** [comment]
It seems I have a very similar issue but it doesn’t seem to be related to being at the end of the file. In fact, I’ve witnessed Zettlr scrolling randomly while I was only reading text, my hands far from the keyboard for at least 20 or 30 seconds. (which means it’s not triggered by some input)

**Comment by nathanlesage** [comment]
I have the suspicion that this is due to a not-so-good state management I've implemented in the tabbing behaviour. So I think we'll finally get rid of this once I moved everything to Vue.

**Comment by josephgarnier** [comment]
I have the same problem that suddenly appeared, unfortunately on long texts, it quickly makes Zettlr unusable :(

**Comment by mattwien** [comment]
I also stopped using it for long texts. The longer the text the higher the intensity of the problem. 800 lines and suddenly it scrolls to the top... you scroll down again- and it is scrolling up automatically instantly.

**Comment by yhancik** [comment]
I've tried downgrading my Zettlr until I find a version that doesn't have the scrolling bug. In my case it seems to be 1.8.0. 
So @nathanlesage, I guess it's something that changed since 1.8.1?

I also confirm it happens on automatic & manual saves.

**Comment by nathanlesage** [comment]
This has been resolved due to major simplifications of both the DOM structure and CSS applied, so the current dev branch should work out of the box already.

**Comment by SamirSaidani** [comment]
Hi, is it possible to download the dev build exe somewhere fixing this bug ? 

It's a really disturbing bug, and I think it would lead some people to give up on zettlr right away: it's like having a kid behind you typing return on your keyboard every seconds, I don't know how people manage to stick to zettlr with such a bug ! In my opinion, this bug should be set at a p3 priority.

Displaying only what you're typing is the main point of an editor, right ?

Sorry for the ranting, I really like zettlr, this is an awesome work, thanks for putting it opensource, I wish (and want) it the best.

**Comment by nathanlesage** [comment]
@SamirSaidani You can – at your own risk – retrieve weekly-published nightlies from https://nightly.zettlr.com

**Comment by SamirSaidani** [comment]
@nathanlesage Thanks for this link: I didn't find the nightly build despite looking hard into the official website... Too late for me, I've already built the package from github, takes me few hours (setup nodes/yarn, reset my previous zettlr config, debug compiling errors...). 
It would be nice for people looking for the "alpha" builds to put the link in the official website, with the usual caveats...
It would have definitely saved me time.

**Comment by solomonfentonmiller** [comment]
I'm still getting this issue on Windows 10 and version 1.8.9! It happens as described here and in https://github.com/Zettlr/Zettlr/issues/1621

Are we sure there isn't another cause?

**Comment by rmejean** [comment]
I'm still getting this issue on Windows 10 too, very distrubing!

**Comment by nathanlesage** [comment]
To all complaining about the bug in the 1.8 line in here: The issue has been fixed in the 2.0.0 branch. Furthermore, the nightlies should be fairly stable at this point, so if this bug is a dealbreaker for you, feel free to switch to the 2.0.0 branch. I cannot backport this to 1.8 due to time constraints.
