### ISSUE TITLE
[Bug] Dataloss when Moving Files with Unsaved Changes

### ISSUE THREAD

**Issue by ploum** [Zettlr/Zettlr#2347]
### Description

It looks like, in Zettlr 2.0, it’s not possible to have opened files saved automatically (I didn’t find the option).

I’ve lost modifications numerous times since trying the 2.0 beta.

1. Shutdown the computer without closing Zettlr and saving first.
2. Moving a file currently edited to a new folder without saving it first.
3. Opening a file already opened in Zettlr in another editor (the old version is then opened and Zettlr restore the old content)

In all cases, modifications are lost without a single warning or hint that data may be at loss.

It should be noted than when you try to close an opened tab with modifications, a warning is displayed. But the button "save" in this warning is not working and does not save the modificatinos.

### Reproducing

1. Open a file in Zettlr
2. Modify it without saving.
3. Open the file in another editor.

### Zettlr Version

Beta (if applicable)

### Your Platform

- [ ] Windows
- [ ] macOS
- [X] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Ubuntu 21.04

**Comment by nathanlesage** [comment]
All of these problems are mitigated by now; there's a very recent beta that should fix most of these issues. Would you mind trying it out? You can specify the autosave again – either off, immediately (250ms delay) or with delay (5s). Plus a few more things have been fixed where I forgot to check if there were changes to a file

**Comment by ploum** [comment]
Autosave seems to work fine, indeed. By default, it was set to "after a short delay". I don’t know if I should make it as "immediately" but, anyway, this will probably prevent most data loss cases.

Note that the underlying problems are not solved. If I modify a file then move it to another folder, all the modifications from the last 5 seconds are silently lost. This will probably be the case with shutdown and I confirm it’s the case when opening a file in an editor with no self-actualisation (Antidote in my case).

Which may lead to very strange and annoying behaviour like last-minutes corrections being discarded/forgotten.

**Comment by nathanlesage** [comment]
Alright, so do I see it correctly that one issue is the "move" command? I recently fixed the rename command, but I did not touch the move command, but that's easy to mitigate. I'll change the issue title for now to correspond to that issue. If you find another one, it would be best to open separate issues (I'm trying to slowly migrate to one issue per issue :D)

> I confirm it’s the case when opening a file in an editor with no self-actualisation (Antidote in my case)

???

**Comment by ploum** [comment]
Of course, handle bug as it’s best for you :-)

I mean that the same problem arises when opening the file with another editor (one that doesn’t detect changes) before the 5 seconds limit. (Antidote is a very famous French spell checker, which is how I detected the issue).

So : 

1. Open a file in Zettlr
2. Modify it in Zettlr
3. Open the file with another editor immediately.
4. See that the file loaded is the one in step 1 (not step 2).
5. This may induces data loss.

**Comment by nathanlesage** [comment]
Ah, now I see what you mean. But this is not something that I could in any way solve algorithmically. I fear, there you're required to make sure to save prior to loading the file externally ;)
