### ISSUE TITLE
[Bug] Cannot delete files

### ISSUE THREAD

**Issue by noah-arroyo** [Zettlr/Zettlr#2368]
### Description

Cannot delete files within Zettlr. 

### Reproducing

1. Attempt to delete a file by any method:
- In file manager, `right-click` target file and select "Delete file"
- With target file selected in file manager, press `delete`
- With target file selected in file manager, select "File" from main dropdowns, then click "Delete file"

2. (File is not deleted)

### Zettlr Version

Beta (if applicable)

### Specify version

2.0.0-beta.3

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

### Additional Information

Someone else flagged a similar issue for 2.0.0-beta.1: https://github.com/Zettlr/Zettlr/issues/2308 

Like them, I'm syncing my Zettlr notes. However, some difference between their situation and mine:

- I can delete files in Windows explorer, and they'll stay deleted.
- I'm syncing using [Box](https://www.box.com/), not Spideroak.
- I've been syncing Zettlr notes with Box for more than a year, and never had this issue before.

**Comment by noah-arroyo** [comment]
I think this issue is somehow related to another: https://github.com/Zettlr/Zettlr/issues/2365

I'd had three workspaces open. I closed all three, then re-opened them. In each, I tried deleting an .md file in Zettlr's file manager.

- In the two workspaces _that are **not** synced_, the files were successfully deleted. They disappeared from both Zettlr's file manager and Windows Explorer.
- In the one workspace _that **is** synced_, the file did not delete. It remained visible and editable in Zettlr's file manager, and it survived in my synced folder view through Windows Explorer.

**Comment by nathanlesage** [comment]
Do the logs show something? Is there an error that the items couldn't be trashed? What you could also attempt is to activate this option in the preferences:

![image](https://user-images.githubusercontent.com/17251683/131881985-173ca99b-5d68-4640-a867-fbc73d71ab1c.png)

If that resolves the error then `trashItem` is somewhat buggy (an Electron API-call). In *that* case what you could do is wait for the next Zettlr nightly and test out if the bug has maybe been fixed in the meantime (I just updated all dependencies).

**Comment by noah-arroyo** [comment]
Here are the logs. I marked the key points below.

![image](https://user-images.githubusercontent.com/53156978/132099958-2a5c193d-bae6-4d59-83f3-799623b581b1.png)

(1 + 2) These lines resulted in the logs when I `right-clicked` the file in Zettlr's file manager and selected "delete file."

The file disappeared from the file manager, but its tab remained open in the editor. 

(3) So I typed new characters in the open file and hit `save`, and this line (and all the others shown below it) resulted in the logs.

**Comment by nathanlesage** [comment]
Hmm … curious. What I will do in any case rewrite the function in such a way that I emit an error message if a file could not be deleted (rather than just write it to the console), since I guess this is definitely something users want to know.

That being said, I have the impression it might actually be the Electron call here, because:

1. Zettlr can delete the file (`fs.unlink` works as you mention), so it's not a permission issue
2. However, trashing the file does not work (using exactly the same parameter)

idk, can you deactivate the trash functionality on Windows? :D

**Comment by nathanlesage** [comment]
Is this still an issue?

**Comment by noah-arroyo** [comment]
No and yes.

Still an issue on Zettlr 2.0.3, if default settings are active. Files will not delete.

But not an issue if, in advanced settings, I check the box "Delete items irreversibly, if moving them to trash fails." Then the files delete.

**Comment by nathanlesage** [comment]
I'm still puzzled as to why the move to trash systemcall fails on your machine ...

**Comment by nathanlesage** [comment]
@noah-arroyo Heya, does this still happen with 2.2.5 or did it fix itself? If not, please try out the next nightly on monday, because maybe the recent Electron update did fix it!

**Comment by noah-arroyo** [comment]
@nathanlesage Apologies for my slow response. Had some stuff to deal with.

This bug appears to be fixed!

...

Some further details and caveats: 

In recent months I've transitioned from Box.com to Google Drive for file syncing. So it's possible that the fix is due to ditching Box, rather than a change on Zettlr's end.

This deletion bug is absent from ver. 2.2.3, which I'm using due to the typing lag that I experience in later Zettlr versions (#3295) -- looks like you're fixing that bug too, for which I'm quite grateful :) 

The deletion bug appears to be absent from the official ver. 2.2.5 too. 

I just tried installing the most recent nightly version of 2.2.5, but once installed it wouldn't open. Weird. And it's the first time I've experienced that with a nightly.  🤷 

(I'm on a Windows 10 comp, installing a .exe file.)

Cheers!

**Comment by nathanlesage** [comment]
> but once installed it wouldn't open. Weird. And it's the first time I've experienced that with a nightly. 🤷

It could be that this nightly is still the one with the Type error which I baked into the codebase for a few days. Iirc I fixed it for the nightly that should be available now on the page, so feel free to try out that one!

(But closing this bug, finally :))
