### ISSUE TITLE
Adding reveal.js plugins

### ISSUE THREAD

**Issue by annargrs** [Zettlr/Zettlr#281]
Apologies if this is explained somewhere, but I couldn't find it in the docs. 

Zettlr exposes a number of Reveal variables that can be set through the `zettlrRevealOptions`, but is it possible to get to the full set of things doable with `Reveal.initialize({...})` ? 
In particular, I'm trying to add a reveal.js plugin, but specifying its inits  in `<script>` in the markdown file doesn't seem to achieve anything.

**Comment by nathanlesage** [comment]
Ouh, never thought of supporting Plugins, but it's a nice idea! Besides, the revealJS-version shipped with Zettlr is almost a year old, so I should be updating anyway …

**Comment by nathanlesage** [comment]
Ah, P.S.: Supporting is easy, just include the plugin script somewhere in the head, and then prior to the `Reveal.initialize`-function you can add the plugin, according to the docs. If that doesn't work, then the revealJS version is *really* outdated :D

**Comment by annargrs** [comment]
Hmm, so far I cannot pass any extra options at all. It seems that Zettlr takes its `zettlrRevealOptions` and passes that to

`Reveal.initialize(zettlrRevealOptions);`

in the end of the file. It ignores any additions to `zettlrRevealOptions` that are not in its pre-defined set, so I cannot pass anything else.

**Comment by nathanlesage** [comment]
> The content of any <script> element in the end of Zettlr file is just ignored

That should not happen… I mean these are only some options, NOT plugins; these seem to be initialised separately, but I've never used those, so I'm not sure how it works — but I'll be watching out

**Comment by annargrs** [comment]
I've got around the problem with extra options by (hackishly) updating the `zettlrRevealOptions` in javascript before they get passed on to the initializer. Imho that's an ugly crutch that should not be necessary, it would be nice if Zettlr just passed along everything it got from the user.

Confirming that it's definitely impossible to add anything that should be executed *after* initialization, any later scripts do not get passed to the output presentation.
So you're saying this should not be happening? Shall we consider this a bug report?

**Comment by nathanlesage** [comment]
> I've got around the problem with extra options by (hackishly) updating the zettlrRevealOptions in javascript before they get passed

So you're using a script-tag at the end of your Markdown-file, right? This might seem a little bit hackish, but I think this is actually a perfect way to ensure both sane defaults for revealJS-presentations for users who don't know JavaScript and flexibility for people who want to tweak the options, just [as I outlined in the docs](https://docs.zettlr.com/academic/presentations/#presentation-settings).

This way you have the comfort of writing your presentations and only need one script- or style-tag each to define everything you would like! :)

Nevertheless, I must be updating the revealJS-library anyways to the newest version!

**Comment by annargrs** [comment]
No, the only place I can put `<script>` is in the head, before the body of the presentation. If it's in the end, it doesn't get passed to the generated file at all. 

So the hack kinda works for updating initialization parameter dictionary, but obviously won't work for anything that should come after  `Reveal.initialize()`. E.g. I can't add an event listener.

**Comment by nathanlesage** [comment]
Ah, yes. This is something else: I need to include the revealJS-Script in the head, and initialise it in the bottom. So basically I'll address this whole block of issues at once! :)

**Comment by nathanlesage** [comment]
Hey, so I just bumped the whole revealJS show to the newest version and added some goodies for maintaining it.

Now the main revealJS-script is loaded in the `<head>`-tag, which means you can alter the `Reveal`-object as you like. As always, you can override the `zettlrRevealOptions`-object and now plugins and other fancy stuff [as outlined in the documentation](https://github.com/hakimel/reveal.js/#readme) should now work!

The new version can either be used by building the current develop branch, or from 1.4-beta.2 onwards! If there are any other issues, please comment!

**Comment by annargrs** [comment]
Ok, giving up after hours of head-bashing with dependencies.

Any chance you could kindly build a beta with this? I'm on linux and not at all familiar with node or yarn, and they both refuse to build the app from develop according to your instructions. Yarn fails due to fsevents, and npm produces garbage.

It's not just the plugins, but also the fact that reveal.js' print-pdf doesn't work at all for me, in any browser. I have a faint hope that it is due to the old reveal and might also be fixed with this update.

**Comment by nathanlesage** [comment]
Ah, that's uncool :/ Which distro are you on? Debian-based or Fedora-based?

**Comment by annargrs** [comment]
Ubuntu 18.04.

I'm seeing a bunch of issues that are all over the place individually, some platform-specific, some not. I'd really appreciate a build, because spending any more time trying to just install it, with a good chance that then it still can't export anything - looks like I should just go back to beamer :(

**Comment by nathanlesage** [comment]
Perfect, I just ran a nightly off the current sidebar-refactor-branch!

Here's a freshly pressed Deb-File: https://drive.google.com/open?id=1YdZ6FMnNCU4BBYWvKsOVsDheKtgF29fr

It's the same installer as for any other version, but obviously not considered stable. Please note that at the current state, virtual directories WILL break the sidebar view. Nevertheless, everything else should work out just fine! :)

(And if you accidentally spot another bug in the sidebar, feel free to report it as well :D)

**Comment by nathanlesage** [comment]
Oh, maybe I should also say what's happened:

1. Reveal.js is now the newest version (3.8. iirc)
2. The library itself is now included AT THE TOP of the file, meaning you have access to the `Reveal`-object throughout your Markdown file.
3. The `zettlrRevealOptions` can now be modified more easily.
4. Only after your document, `Reveal.initialise(zettlrRevealOptions)` will be called, including all modifications you've made.

So you should be able to use plugins by using something along the lines of this:

```html
<!-- Some Markdown code up here -->

<script src="/absolute/path/to/your/plugin.js">
/* Please note that you only need to provide such a script tag with the full path to your plugin, if you don't define it inline! The plugin must be included before you register it with Reveal. */
</script>
<script>
Reveal.registerPlugin( 'myPlugin', MyPlugin);
<script>

<!-- Some more maybe here -->
```

**Comment by annargrs** [comment]
Thanks a lot! 

So printing to pdf did not work out of the box (only 1 slide was exported). But it worked after the following:

1) adding [pdf.css](https://raw.githubusercontent.com/hakimel/reveal.js/master/css/print/pdf.css) file to the exported html file folder;
2) adding the following script to the file head:

```
<script>
  if( window.location.search.match( /print-pdf/gi ) ) {
    var link = document.createElement( 'link' );
    link.rel = 'stylesheet';
    link.type = 'text/css';
    link.href = 'pdf.css'; // the path to the pdf.css file
    document.getElementsByTagName( 'head' )[0].appendChild( link );
  }
</script>
```
Perhaps these fixes should be integrated in Zettlr?

Reveal.js pdf export works as follows: add `?print-pdf` to the end of your `slides.htm` url, so it becomes `slides.htm?print-pdf`.

**Comment by nathanlesage** [comment]
Perfect — does it also work with the print.css also loaded while looking at it? Should be, right? It would be easy to simply minify and add the print.css to the template as well — then you could simply print by pressing Cmd/Ctrl+P in the browser – would be much more easy!

**Comment by annargrs** [comment]
You mean `pdf.css`, not `print.css`, right? I just tried minifying and adding it to the style section. That didn't make ctrl+p work for me, but maybe I didn't do it right. 

Confirming that my plugin does work, loaded in the end of the file as you described (I tried 'chalkboard').

**Comment by nathanlesage** [comment]
> Confirming that my plugin does work, loaded in the end of the file as you described (I tried chalkboard).

Heureka! 🙌

Concerning the CSS files, I'll check it out and see what I can do!
