### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by Sisi-Wiciel** [Zettlr/Zettlr#390]
## Description
Citations not rendering anymore. None of my formerly rendering citations would render anymore. They are not recognized as citations when starting with the leading "@" character. The "View attachments" sidebar shows the message "References: Could not update bibliography!". I updated the database from Zotero, reconnected the file in the preferences.

**Screenshots**
![Screenshot_20191111_055214](https://user-images.githubusercontent.com/21168981/68551413-d1f67300-0447-11ea-9c5c-054fff1520ba.png)

## Platform
 - OS: manjaro
 - Zettlr Version:1.4.3

## Additional information
It is similar to this issue:https://github.com/Zettlr/Zettlr/issues/261, but the size of my json file was 68.8 KiB

**Comment by Sisi-Wiciel** [comment]
I reinstalled the app, and the console showed nothing wrong, but the citations still can't be renderer.
![Screenshot_20191111_061431](https://user-images.githubusercontent.com/21168981/68551721-d2443d80-044a-11ea-9f08-83c5055d527f.png)

**Comment by nathanlesage** [comment]
This can have several reasons. First, it might be that library upgrade introduced a wrong citekey. From 1.4.3, a lot more symbols are allowed, but apostrophes, e.g., are still invalid. If you're using a `BibTex`-library, it miiiiiiiiiiight be something with Astrocite (the library that parses those files) but I'm not sure… can you try to figure out what has changed in your library between the last upgrade and before?

**Comment by Sisi-Wiciel** [comment]
Thanks. I changed the json file and it worked!

**Comment by nathanlesage** [comment]
Perfect! Just so that I know what to look out for, if other people have the same problem: What did you change so that it worked again? Was there indeed a citekey problem? :)

**Comment by brimwats** [comment]
@Sisi-Wiciel what did you do to the JSON file to make it work?

**Comment by brimwats** [comment]
I figured it out. For future people: do **not** follow the instructions [here](https://docs.zettlr.com/en/academic/citations/) and use Better CSL JSON. Instead use BetterBibTex format. 

@nathanlesage you might want to update documentation

**Comment by nathanlesage** [comment]
@brimwats But with what? Better CSL JSON is working perfectly for a lot of people, so it is **not about the format**, but there's something else. And I need to know what it is if I'm about to update the documentation.

**Comment by Sisi-Wiciel** [comment]
@brimwats It was a bug of Better CSL JSON on majaro system. I followed the steps from this [ issue] (https://github.com/retorquere/zotero-better-bibtex/issues/1316#issuecomment-554934790)

**Comment by nathanlesage** [comment]
@Sisi-Wiciel Thanks for sharing the information!

**Comment by mgiugliano** [comment]
I have the same problem (under macOs). I am almost sure the culprit is something wrong in my current BibTex file.

@nathanlesage, is there any way to see what in my *bib (or even *json converted) file is making Astrocyte unhappy? My Bib file opens perfectly with BibDesk or JabRef.

**Comment by nathanlesage** [comment]
I'm sure it's not astrocite but that there are some malformed CiteKeys that Citr doesn't let pass. I'm not sure if I fixed this in the last beta or if it will come with the next, but Zettlr should/will tell you which citekeys are malformed (mostly because of special characters, such as [ or ] within them)

**Comment by mgiugliano** [comment]
Thank you! 

By downloading and launching the 1.5.0beta, I could - as you anticipated - identify the "annoying" cite key in a blink of an eye. I then amended my BibTex file and now Zettlr works with it!

**Comment by nathanlesage** [comment]
:) Glad it works now!

**Comment by efficacy** [comment]
Just to add that this is still really annoying in 1.7.5 and better, but still not entirely right, in 1.8.0 beta.

I love Zettlr, but it has problems with non-ASCII characters. I would not mind if this just meant that the individual reference was ignored. I would happily find and fix that if and when I actually need to cite it. The bigger issue is that any minor incompatibility completely stops the whole referencing component, presumably because the "Cannot read property 'replace' of undefined" error is not caught or prevented while reading individual records.

I'm a software developer myself, so I have grabbed the current 1.8.0 beta develop branch from GitHub and that seems to _partly_ fix this problem. Non-ASCII characters in citation keys no longer prevent citation lookup, but they render incorrectly. The same non-ASCII characters now seem to be stripped out of the authors' names. For example Møller becomes Mller. I can understand imposing rules on valid characters for citation keys, but an author name should never be messed with!

Note that I use Mendeley as a reference manager, and it produces a bibtex file with LaTeX sequences for such characters. In this case an example problematic bibtex entry is as follows:
`@article{Møller2007,
abstract = {XSL Transformations (XSLT) is a programming language for defining transformations among XML languages. The structure of these languages is formally described by schemas, for example using DTD or XML Schema, which allows individual documents to be validated. However, existing XSLT tools offer no static guarantees that, under the assumption that the input is valid relative to the input schema, the output of the transformation is valid relative to the output schema. We present a validation technique for XSLT based on the XML graph formalism introduced in the static analysis of JWIG Web services and XACT XML transformations. Being able to provide static guarantees, we can detect a large class of errors in an XSLT stylesheet at the time it is written instead of later when it has been deployed, and thereby provide benefits similar to those of static type checkers for modern programming languages. Our analysis takes a pragmatic approach that focuses its precision on the essential language features but still handles the entire XSLT language. We evaluate the analysis precision on a range of real stylesheets and demonstrate how it may be useful in practice.},
author = {M{\o}ller, Anders and Olesen, {\O}sterby and Schwartzbach, Michael I},
file = {:C$\backslash$:/Users/Frank/AppData/Local/Mendeley Ltd./Mendeley Desktop/Downloaded/M{\o}ller, Olesen, Schwartzbach - 2007 - Static Validation of XSL Transformations.pdf:pdf},
journal = {ACM Trans. Program. Lang. Syst. Article},
keywords = {Algorithms,Categories and Subject Descriptors,D24 [Software Engineering],D32 [Programming Languages],DTD,I72 [Document and Text Processing],Languages,Software/Program Verifica-tion—Validation,Verification Additional Key Words and Phrases,XML Schema,XSLT,inbox,phd,static analysis},
mendeley-tags = {inbox,phd},
number = {10},
title = {{Static Validation of XSL Transformations}},
volume = {29},
year = {2007}
}`

**Comment by nathanlesage** [comment]
> For example Møller becomes Mller. I can understand imposing rules on valid characters for citation keys, but an author name should never be messed with!

This has nothing to do with the Citr library – I would rather assume there's an error in the Astrocite library which we use to parse BibTex files. It almost seems that [Astrocite](https://github.com/dsifford/astrocite) cannot handle non-ascii characters (it is marked as WiP, so this is not surprising), but Zettlr itself …

- opens all files with UTF-8 support
- passes almost any citation key (even @Møller will parse just fine)
- uses [citeproc](https://github.com/Juris-M/citeproc-js) to retrieve the keys itself, which is pretty robust (as demonstrated by it being used in Zotero)
- uses Astrocite to parse bibTex to CSL JSON as the latter is the internal format.

Please attempt to have a look; as I'm not using BibTex libraries myself and lack the time to extensively test it, this would help immensely in locating the problem. Then, please feel free to open up specific issues for all bugs you found, including potential mitigation.

Thank you for your help in this regard.

**Comment by efficacy** [comment]
Thanks for the pointer. I'll take a look at the astrocite code to see if I can get it to work properly with my big bibtex collection. If I can get it working, I'll submit a pull request to that project.

**Comment by efficacy** [comment]
FYI I have now created a PR on astrocite ( https://github.com/dsifford/astrocite/pull/34 ). Now it's up to that project team. I don't know how active they are, though.

**Comment by nathanlesage** [comment]
Cool, thanks a lot for already fixing the issue! When Astrocite publishes a new release, I'll make sure to update afterwards, then the bug should be gone!

**Comment by efficacy** [comment]
@nathanlesage FYI astrocite has now bumped to version 0.16.4 which includes my patch. Feel free to update your dependencies the next time you touch package.json.

**Comment by nathanlesage** [comment]
> @nathanlesage FYI astrocite has now bumped to version 0.16.4 which includes my patch. Feel free to update your dependencies the next time you touch package.json.

Thanks, will do!
