### ISSUE TITLE
Multiple bugs with comment function

### ISSUE THREAD

**Issue by noah-arroyo** [Zettlr/Zettlr#4340]
### Description

(Uncertain if this should be split into multiple issues.)

**Expected behavior:** 

1. A comment remains intact even if the user types a space after the comment's closing phrase (`-->`).
2. Comment-style rendering applies only to text inside the comment's bounds.
3. Text within a comment isn't tallied in the word count.

**Buggy behavior:** 

1. When the user types a space after a comment's closing phrase (if that comment does not begin a line), auto-correct turns `-->` into `→`, which disables the comment.
2. When a comment begins a line, comment-style rendering applies to all text in that line, including text occurring outside the comment. When this bug occurs, bug No. 1 will not occur in the same line.
3. Zettlr's word-count function counts the text inside the comment, as well as the comment's opening and closing phrases ("`<!--` this is a comment `-->` and this is text outside the comment" is counted as 13 words).

### Reproducing

(Already explained above.)

### Zettlr Version

Beta (if applicable)

### Specify version

3.0.0-beta.4

### Installation Method

From the Website or GitHub

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Windows 10

**Comment by justjack2347** [comment]
@josh-133, @Mr-Verb and I will look to tackle some of this over the next week or so.

**Comment by justjack2347** [comment]
Hi @noah-arroyo. Using release 3.0.0-beta.4 on a Windows 11 operating system, I am unfortunately unable to reproduce the first bug, however can reproduce both other bugs as noted. Hopefully either @josh-133 or @Mr-Verb can replicate your issue so we can find a solution. Cheers

**Comment by justjack2347** [comment]
I have found an instance where the first bug can be reproduced. I was able to reproduce it when using the command "ctrl-shift-c" to create a comment around a selected piece of text. When doing this however, the comment styling bug does not occur. @noah-arroyo, was this sort of behaviour consistent with what you were experiencing or could you face all bugs at the same time?

**Comment by Mr-Verb** [comment]
Did you mean this release: [Release v3.0.0-beta.4](https://github.com/Zettlr/Zettlr/releases/tag/v3.0.0-beta.4)? I downloaded the source code and ran yarn test-gui but cannot recreate the issue where the closing comment tag auto corrects to an arrow. I am on a windows 10 system running a WSL terminal. 

I can recreate buggy behaviour 2 and 3 though

**Comment by josh-133** [comment]
I am also able to recreate buggy behaviour 2 and 3, but can't recreate the end of a comment autocorrecting to an arrow. I am on a windows 10 system with an intel CPU running a WSL terminal as well.

**Comment by noah-arroyo** [comment]
A few things:

@justjack2347, you said:

> I have found an instance where the first bug can be reproduced. I was able to reproduce it when using the command "ctrl+shift+c" to create a comment around a selected piece of text. When doing this however, **_the comment styling bug does not occur._** @noah-arroyo, was this sort of behaviour consistent with what you were experiencing **_or could you face all bugs at the same time?_**

I've bold/italicized the parts of your message that I don't understand. Can you explain further?

...

@Mr-Verb yes, sorry, I'd meant to say v3.0.0-beta.4, not v4.0.0-beta.4. I've corrected this in my opening message. Thanks.

...

The first bug will only occur for a comment that does not begin a line (I've updated my opening message to reflect this). @justjack2347 @Mr-Verb @josh-133 if you haven't already, can you test this bug with a comment that starts mid-paragraph?

**Comment by justjack2347** [comment]
@noah-arroyo, I hope this explains things a bit better:

- The comment styling bug was in reference to your second buggy behaviour point where the comment-style renders outside of the comment symbols ('').
- The text "or could you face all bugs at the same time" was regarding whether you would have all three of the buggy behaviours that you mentioned occur at the same time since we were only able to reproduce two of the three by either manually writing the comment symbols or inserting a comment around selected text using the "ctrl+shift+c" command.

With your answer however, you were able to address both of these and so no issues there. I was able to reproduce the bug with a comment starting mid-line on the Windows 11 setup with the Zettlr v3.0.0-beta.4. Thanks for your response

**Comment by noah-arroyo** [comment]
Thank you!

**Comment by justjack2347** [comment]
@nathanlesage, cheers for the fixes, you beat me to it! I had been working on the inline comments being removed due to autocorrect since I was eventually able to reproduce this. I could be wrong but I think there is still a problem with inline comments with the  changing either and so the inline comment should not have any problems. The only annoying this about this change is that in the preferences under the autocorrect replacements, '/(?<!<!)--/' is a lot more confusing than '--'. Let me know if you have any thoughts regarding this. Cheers

**Comment by nathanlesage** [comment]
See my comment in your PR! Also for @noah-arroyo -- you can prevent `<!--` autocompleting by adding a space in front of the autocorrect key in the preferences, then it'll only autocomplete those two dashes when there's a space in front.

**Comment by noah-arroyo** [comment]
Gotcha. Thanks to all for your hard work on this. This is exactly why 
Zettlr is such a stand-out tool.
