### ISSUE TITLE
[Zettlr 3.0.x] Save Issues: Main Issue

### ISSUE THREAD

**Issue by khakhalin** [Zettlr/Zettlr#4959]
### Description

I think it may be the same issue as this one: https://github.com/Zettlr/Zettlr/issues/4628
but it is marked as closed, despite one (now three haha) comments about the issue persisting already after the issue was closed, and I'm not sure how to reopen it. So reporting it anew here.

What happens is that Zettlr doesn't detect some files as changed, which means that you lose all changes with them. If you try to use autosave, they are never saved, and you keep losing all changes. If you switch to manual save, then the first time you save them, it does it silently. The asterisk (the one indicating change) never appears, and thus never disappears, and you don't know if the file is save or not. In most cases it is saved, _but sometimes it is not_! And I'm not sure what the pattern is.

Once the file is saved however, at least once, if you reload Zettlr, it's starting to get tracked (the asterisk appears as you edit it).

### Reproducing

The issue seems to be specific to files that were created on Mac, and then brought to Win 11 via Git, and/or opened in the latest verson of Zettlr. Until 2 weeks ago I worked with same very files on Win 10, with a slightly older version of Zettlr, and everything worked perfectly. On this new system, with new files, also everything works. But for old (Mac-origin) files on this new system - I'm lost in a limbo. Basically for every file I'm editing I have to check if Zettlr is detecting changes, and if not, add a trivial change, save the file, close Zettlr, start it again, check if the file now behaves normally. If not, repeat.

### Zettlr Version

Stable (most recent version)

### Installation Method

None

### Your Platform

- [X] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [X] Intel 64bit
- [ ] ARM 64bit

### Operating System Version

Win 11

**Comment by kerryland** [comment]
Funnily enough, I was the person who opened https://github.com/Zettlr/Zettlr/issues/4628 back in September, but haven't done much with Zettlr until today when I thought I'd try again.

Sadly, I'm in the same boat as you. Zettlr's ability to detect external changes, and habit of ignoring explicit requests to save a file, are still here.

Here's *one* way to confuse Zettlr 3.0.5 on Windows 10. I suspect there are others.
- Open a folder in Zettlr
- Create a file in Zettlr, eg: `x.md`, in the folder.
- Save the file **and close the tab**
- Externally, append to the file. From a Windows prompt I used:
```
echo "Hello" >> x.md
```
- Within Zettlr, click on `x.md`. Notice it does *not* contain the freshly appended text from the command line.

I have also, today, put Zettlr into a state where it does not notice changes made within the editor, and so ignores your "save" command. I think it might be related to timestamps "rolling back" due to git reverts. I'm not sure. I'll come back in another 6 months and see if things have improved.

**Comment by nathanlesage** [comment]
@kerryland Oh, so I don't know why I closed the other issue but your description of how the bug appears has given me the hint I needed to understand what's happening. One big issue I'm still dealing with is proper synchronization between open documents and open editors. Ideally, we would want to just close files that are closed anywhere in the app. Then we would have no problem detecting any changes because that logic already works flawless in the file tree, and we would read in the most recent state when the file is reopened.

But don't fret: I know that I am deeply dissatisfied with how the document manager works now, so I will get to fixing it soon.

**Comment by khakhalin** [comment]
I wonder then if my case, and also why it behaves differently on 2 computers, may be related not to a different Win or Zettlr, but to a different git. In both cases I pull files from a repo (that was updated from a Mac for about 2 years), but one git keeps silent about it, while the other one gives me these messages at _commit_ (not at pulling): `in the working copy of 'keywords/scrum.md', LF will be replaced by CRLF the next time Git touches it`. So I wonder if this Mac2Win transformation happened in 2 different moments for 2 different machines, making Zettlr confused in one case, but content in the other...

Fingers crossed that it can be fixed haha! :) And gosh, you just wanted to write your PhD comfortably; now you have to care about this CRLF crap, what a world! :)

**Comment by kavir1698** [comment]
I am having this issue too. At first, I thought there is problem with auto save. So I turned that off. Now I see that I edit a document, but the document tab doesn't show as it is changed. Clicking the save button doesn't do anything either. Also, git doesn't see any changes. If I close the tab and open it again, the changes are gone! I am on Windows.

**Comment by nathanlesage** [comment]
I now decided to close the other issues so that we can focus on this issue. There was lots of useful knowledge for me spread out in those issues, so please, comment any observation you have here. I have already some ideas as to how I might be able to solve this issue, but I'm not quite there. Please keep the info coming, I'll get to this soon.

**Comment by khakhalin** [comment]
OK a quick recap. I worked on a body of Zettelkasten from a Mac for 2 years (not sure if it's relevant?). Then cloned it on a Win computer. In the past it worked perfectly (on a different machine, with older version of Win, slightly older version of Zettlr, and using git). This time it's Win 11, laatest Zettlr, and gitbash for synchronizing.

In this setup, upon the first edit of any file, all edits are lost. At first all edits were lost, period, as I was in the "autosave" mode, Zettlr wouldn't detect that the file is changed, and then it wouldn't save it. Upon reading one of your old threads, I moved to manual save mode. In this mode the following thing happens:
1. You open a file, you edit it. Asterisk of change doesn't appear. If you now close the file, nothing will happen, and you won't progress to step 2.
2. If you do save the file with Ctrl-S, git notices the change. Now there's something to commit. However in practice this change is bound to be lost: if you close Zettlr and re-open it, the change is gone (even tho git still claims there's something to commit).
3. However upon this 2nd opening of Zettlr (which is critical), something changes and the file becomes normal. So you need to close Zettelr. Once it reopens the file, it recognizes it as its own, an asterisk appears upon edits, and from now on all changes are saved.
4. It is possible to break this sequence and have the file un-saved and invisible again, but I'm not sure when it happens. I suspect that it may be happening if you commit the file after stage 2, but before stage 3. But I'm not sure. Only happened for me once.
5. For newly created files everything is always fine.
6. I suspect the problem has something to do with CRLF/LF thing, as gibash is also telling me something about forcing this transition at the first commit, which means that technically it edits the file while it is open by Zettlr, which may upset Zettlr, I imagine. But it's still a bit weird, as it used to work before (on a different machine), and the default value for git `core.autocrlf` was always False, as far as I can tell.

**Comment by kyaso** [comment]
> I suspect the problem has something to do with CRLF/LF thing

I have also faced this: https://github.com/Zettlr/Zettlr/issues/4628#issuecomment-1713663726

I remember there was a warning in the logs that the file size mismatched with what Zettlr was expecting, and hence couldn't save any changes from then on.

**Comment by kerryland** [comment]
> LF will be replaced by CRLF the next time Git touches it

I too see git messages like this.

**Comment by nathanlesage** [comment]
Alright, so there are two things. First, what @khakhalin and @kerryland experience is some issue that I believe may be an interaction with my (very bad) state management and how git treats whitespace. I believe that the CRLF issue may point to the right direction. For Zettlr, any byte change of a file is a change, but git may decide that, e.g., CRLF and just LF are interchangeable. I don't know too much about git's behavior here to give a proper explanation, but it sounds not too far off.

The important part is that here there is a weird interaction between the operating system (a.k.a. your actual files) and how Zettlr treats them in the main process (a.k.a. what manages your files, changes, and that you can't see).

Then, the issue that @kyaso experiences has something to do with the other part, i.e. an interaction between Zettlr's main process (that manages the documents) and the renderer window(s) that display the files. The error that there was a "wrong document length" indicates that Zettlr's main process has just reloaded the document from disk (thereby creating a new "Document" instance) while the renderer (a.k.a. the editor that you see) still had the old document instance, and attempted to push changes that only work with the old one (think editing history) into the new one, which the main process did not allow.

The diagram of how it is at least supposed to work is the following, maybe @kyaso can make something out of it:

![image](https://github.com/Zettlr/Zettlr/assets/17251683/26226f4b-14d2-46aa-b71e-4b529e4c554d)

***

#### Relevant Code

Main process code (Document authority functions within the document manager, I want those two to become separate classes):

https://github.com/Zettlr/Zettlr/blob/d5011287ca5f158e5606c21d1edd6c6b4a1accc8/source/app/service-providers/documents/index.ts#L578-L719

Renderer code:

https://github.com/Zettlr/Zettlr/blob/develop/source/common/modules/markdown-editor/util/ipc-api.ts

**Comment by nathanlesage** [comment]
Another thing; @kyaso I just re-read your comment, and while the newline as single unit-aspect you mentioned doesn't relate to the document length error you've been getting, we should set the corresponding line separator facet with whatever the line endings are for the file in question just so that CodeMirror uses those whenever we retrieve the document as a string ...

**Comment by internationils** [comment]
CRLF / LF could be a topic for me too. My files are in Dropbox, and I'm sometimes using Zettlr & Notepad++ (and another editor) on Win, and 1 or 2 different markdown editors on iOS devices.

**Comment by jgsw** [comment]
To confirm what others have said, it does seem to be CRLF/LF related. I'm on Windows (and syncing using OneDrive). I used to get saving problems whenever I edited a Zettlr file externally in VS Code. 

I did a bit of digging, and discovered that VS Code on Windows defaults to CRLF. After I changed VS Code to save with LF, I no longer see the save bug.

**Comment by khakhalin** [comment]
Yeah, btw, an update from me: while the suggested solution was to update to the newer version, it didn't help. I think I'll need to solve this CRLF thing somehow. Maybe reconfigure the repo idk and clone it again. But it looks like something to be solved outside of Zettlr, unfortunately. Too niche and too weird :)

**Comment by kerryland** [comment]
> Too niche and too weird :)

I'm not sure that using Windows is *that* niche...

**Comment by nathanlesage** [comment]
> To confirm what others have said, it does seem to be CRLF/LF related.

You're in luck: I finally had some spare time and got to re-implementing proper linefeed handling. From now on it *should* work fine again.

I will immediately initiate a nightly build, so have a look in ~an hour at the link and try it out. This should fix this issue (hopefully): https://nightly.zettlr.com

**Comment by nathanlesage** [comment]
In case anyone is interested what happened: after migrating to CodeMirror 6, I properly split a file using its line endings, but when I saved it I always just used newline characters, effectively changing the actual line feeds. This means that, when a file externally was reset to the original linefeeds, Zettlr was confused because the file modification timestamp was different but the content looked the same. I think this could even explain some issues with cloud sync providers such as OneDrive.

If that really is the solution, I'm very sorry since this should never have happened and it was a simple two-line fix. But alas, I'll wait until you report that the most recent nightly actually solves this issue before celebrating ;)

**Comment by jgsw** [comment]
Thanks! The problem seems solved for me with .md and .qmd files. I'm still getting the error if I edit a  **.yml** file that was saved with CRLF line endings.

**Comment by nathanlesage** [comment]
@jgsw Does closing all files, and then clearing the cache and reopening everything work? I double checked and code files also properly detect the line endings, but the previous "wrong" line endings might still be part of the file cache.

**Comment by jgsw** [comment]
I tried clearing closing all workspaces, and clearing the cache, but the problem remains with the .yml file.  

I've attached a zipped minimal example. I am unable to edit this file with Zettlr on my system: I get the "Document out of sync" error. I just created this file, so the file can't be failing as a result of already being in the cache.

[minimal example.zip](https://github.com/Zettlr/Zettlr/files/14652599/minimal.example.zip)

**Comment by khakhalin** [comment]
I updated to a nightly, and not only the problem isn't solved, but it got worse haha (rofl): now it cannot save anything:
<img width="692" alt="image" src="https://github.com/Zettlr/Zettlr/assets/17154125/9cfbfba2-276a-4e46-8ece-0c0d116e0ec7">

Probably just a wrong nightly haha (judging from the messed-up icons row on top), I was just too slow to react, I'm sorry. I'll downgrade to the latest stable release for now, but I hope this thread will keep me posted :)

**Comment by nathanlesage** [comment]
That nightly looks old -- please try the most recent beta, that includes the (hoped for) fix

**Comment by khakhalin** [comment]
I tried the one that is shown as the latest one on the Downloads page right now, but I can try again tomorrow, when it changes :)

**Comment by nathanlesage** [comment]
I meant that you should be able to use the most recent beta, not nightly, here: https://github.com/Zettlr/Zettlr/releases

**Comment by nilsi01** [comment]
![image](https://github.com/Zettlr/Zettlr/assets/112413090/054f5534-96f9-4058-b720-c331f7303701)

Tried the most recent beta.

**Comment by rdhutchins** [comment]
Is this confirmed fixed in nightly?

**Comment by nathanlesage** [comment]
> Is this confirmed fixed in nightly?

I think so, yes.

**Comment by rdhutchins** [comment]
> > Is this confirmed fixed in nightly?
> 
> I think so, yes.

It wasn't fixed for me in the April 8 nightly, see more details here: https://github.com/Zettlr/Zettlr/issues/5109#issuecomment-2053703061
