### ISSUE TITLE
[bug?] Mathmode fractions dont render in HTML exports

### ISSUE THREAD

**Issue by lgalke** [Zettlr/Zettlr#504]
## Description
In HTML exports, `\frac` is not correctly rendered by MathJax.

## Reproducing
Put `$\frac{a}{b}$` in a document and hit Ctrl-P.
The fraction renders nicely in zettlr's in-line preview but not in exported html.

## Expected behaviour
Properly rendered formulas in HTML exports.

**Screenshots**
![image](https://user-images.githubusercontent.com/3439126/73851142-48c7c000-482d-11ea-9d5a-3bb9ad743ac6.png)

## Platform
 - OS and version: MX Linux 19 (based on Debian 10)
 - Zettlr Version: 1.5
 - Screen Resolution: doesn't matter
-  Pandoc version: pandoc 2.2.1 Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.5

## Additional information

I could not trace down the problem further than distilling a minimal example which consists of the fraction command. It is not triggered by conflicting markup elements such as `_`. Further escaping did not help. Double dollar signs  for display math also make no difference. Cannot exclude that I missed something. MathJax should actually render fractions.

Resulting HTML is:

` <p><span class="math inline">$\frac{a}{b}$</span></p>`

- Could it be some MathJAX delimiter config problem? Formulas without `\frac` work flawlessly though.
- Zettlr's export problem, i.e. pandoc, I guess?
- Some stupid mistake on my side?

**Comment by nathanlesage** [comment]
Wait, let me have a look … ah, yes.

So, in the default Pandoc HTML template there is this section:

```
$if(math)$
  $math$
$endif$
```

So I'd need to add this to the default template. Then, the question of which engine to use. Pandoc supports several ones. KaTeX is shipped with Zettlr, however it's buried within the ASAR and external software cannot access this. So it'd be dependent upon either to include the KaTeX stuff into the rendered HTML (standalone, but some work needs to be done in that case) _or_ simply link to the CDN, which will work while connected to the internet (which I personally would assume is fine for most use-cases). This latter case would also make it also Pandoc-compliant, as we'd only use internals by Pandoc!

**Comment by lgalke** [comment]
Thanks for confirming the issue on other systems. This drove me a little mad last night :+1: 

It'd be great if one could expect that math that renders properly inside zettlr would also render properly in exported html. If zettlr uses KaTeX internally, this might be preferable also for html exports.

 I think linking the KaTeX CDN would be fine.

Maybe on the long run it could be feasible to have a "standalone" switch? This could trigger bundling things like KaTeX into the HTML export and, for instance, also gathering local images and copying them over to the export. But I guess this would be a completely different issue.

thanks!

**Comment by nathanlesage** [comment]
Yeah, the thing is as I normally don't use Math and as the software is primarily aimed at researchers in the social sciences, the Math support was always a little bit dim. However, there's no harm done in adding more and more support :D 

A standalone version would have the drawback of bigger file sizes, obviously (I don't know from the top of my had how big the KaTeX files are), and also include them in any HTML file, even if there are no math equations.

Concerning the local images and putting them into the HTML, it's strongly advised not to (it's also not being done even with revealJS-files) because they'd have to be converted to base64, which increases the size by about 30 percent. This is the major drawback with having binary data in text files … but anyway, this would indeed be a different issue, but also not pressing :)

**Comment by lgalke** [comment]
I totally agree that it would not make sense to export standalone per-default. It could be like another option "Export"->"HTML Directory (standalone)"

I was not thinking of putting binary data in text/html files but rather export to a html directory instead of a file.

Like create a structure like this:
/html_output/*.html
/html_output/js
/html_output/img

This would have some advantages when you dump a project or your whole zettelkasten at once. JS deps like katex would, in this case, only need to be bundled once.

Anyways, just ideas, not pressing to solve the current issue! ;)

**Comment by nathanlesage** [comment]
> I was not thinking of putting binary data in text/html files but rather export to a html directory instead of a file.

Have you tried to export a Textbundle? It's exactly that. :D Or textpack, if you want a zip.

**Comment by lgalke** [comment]
Hah thanks! :+1: :100:

**Comment by nathanlesage** [comment]
And here we go

**Comment by lgalke** [comment]
Hey @nathanlesage 
Thank you for the effort.
For some reason these changes did not fix the problem.
I'm on Zettlr 1.6 and pandoc 2.9.2 (Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2)

And **fractions** still don't render properly in reveal.js exports, see screenshot below:

![image](https://user-images.githubusercontent.com/3439126/76433719-0279f980-63b5-11ea-8491-33514c18aed6.png)

and also not in plain HTML
![image](https://user-images.githubusercontent.com/3439126/76433801-23dae580-63b5-11ea-92ef-a42dc4d31d0e.png)


Related: Mermaid graphs seem to have the same problem

![image](https://user-images.githubusercontent.com/3439126/76433946-5258c080-63b5-11ea-837e-a11aca38ab1b.png)


Any Ideas? For Mermaid, maybe again just adding the CDN would help. But these mathmode fractions are really strange, especially because other math renders well.

**Comment by nathanlesage** [comment]
Mh, what does Pandoc say when exporting? It looks pretty much like a Pandoc issue at this moment, but I'm not sure — Zettlr doesn't do anything to your files on export, so it's totally dependant on Pandoc!

**Comment by lgalke** [comment]
So I did some analysis with pandoc:
```
[lukas@nephthys Communication]$ pandoc CrossPM-QAktiv.md -t html -o crosspm-qaktiv.html # frac not rendered
[WARNING] Could not convert TeX math '\frac{1}{N}', rendering as TeX
$ pandoc CrossPM-QAktiv.md -t html --standalone --mathjax -o crosspm-qaktiv.html # frac rendered
$ pandoc CrossPM-QAktiv.md -t html --standalone --katex -o crosspm-qaktiv.html # frac rendered
$ pandoc CrossPM-QAktiv.md -t html --katex -o crosspm-qaktiv.html # frac **not** rendered
$ pandoc CrossPM-QAktiv.md -t html --mathjax -o crosspm-qaktiv.html # frac **not**rendered
```
Using the default pandoc html template.

So it should work when either `--katex` or `--mathjax` is supplied *and* `--standalone`.

In your commit 41a243a77d50bbdfd83e28a1c7ea4344c3d0cffb  I see that there is `$standalone$` is considered as a variable, but is it really set in the concrete case?

**Comment by lgalke** [comment]
For revealjs I needed to actually download reveal.js package via npm and put it in the same directory. Then it works just fine with `--katex` (or `--mathjax`) and `--standalone`. (Guess I could alternatively adapt --resource-path to point to global node_modules)

**Comment by nathanlesage** [comment]
Ah, revealJS-exports are not standalone from the perspective of Pandoc because I need to bundle the files together _after_ Pandoc has run. So it should be solved by manually adding the Katex-stuff to the revealJS-template

**Comment by lgalke** [comment]
There is another ``--self-contained` (implies `--standalone`) for html exports which bundles all dependencies together. But it still depends on relative ./reveal.js path so it would not solve the problem.

That aside, in current zettlr release the frac export does also not work properly for plain HTML output. So it must be also some other problem unrelated to revealjs? Do you always supply `--standalone` for html exports after all?

**Comment by nathanlesage** [comment]
I just had a revelation what happened — did you read the "Breaking Changes" section of the changelog? For me exporting works, because I added the MathJax-flag!

**Comment by lgalke** [comment]
Oh this is a thing which I actually forgot about. 

**HTML output works perfectly fine now**

But still not revealjs

This is with `--katex` added, saved, restarted zettlr to make sure.

![image](https://user-images.githubusercontent.com/3439126/76529052-06b81c80-6472-11ea-89bf-b10a37cc29bb.png)

This is with `--mathjax` added, saved, restarted zettlr to make sure.

![image](https://user-images.githubusercontent.com/3439126/76529376-7b8b5680-6472-11ea-867c-9119c5aa6f43.png)


So I presume there is a tiny remaining issue remaining regarding HTML template vs revealjs template. I'll continue to try figuring it out :)

**Comment by lgalke** [comment]
Got it. It *was* the `--standalone` switch causing the problems

Here's what I get by adding *both*: `--katex` and `--standalone` to pandoc command in zettlr:

![image](https://user-images.githubusercontent.com/3439126/76530013-6105ad00-6473-11ea-98a5-f59acacee9e9.png)

It's not urgent as this workaround gets the job done, but it seems like the `$standalone$` variable is not set correctly for revealjs export.

**Comment by lgalke** [comment]
Just for later reference, this is my adapted pandoc command to make both math and mermaid diagrams work:
```
pandoc "$infile$" -f markdown $outflag$ $tpl$ $toc$ $tocdepth$ $citeproc$ $standalone$ --pdf-engine=xelatex --katex --standalone -F mermaid-filter -o "$outfile$"
```
Mermaid diagram export depends on [mermaid-filter](https://github.com/raghur/mermaid-filter)

**Comment by nathanlesage** [comment]
Alright, I'll have a look at this! Thank you for investigating.
