### ISSUE TITLE
[v4.0.0-beta.4] Significant CPU usage when opening document with large number of ZKN links

### ISSUE THREAD

**Issue by kyaso** [Zettlr/Zettlr#6057]
### Description

When opening a markdown file with a lot of ZKN links `[[ ]]` (>500), there is a constant noticeable CPU usage by Zettlr. Of course, I can't give comparable numbers on the usage, as every computer is different, but on my machine, even when idling (i.e. Zettlr is opened in the foreground, but we are not interacting), Zettlr stays at the top in task manager with 10-15% CPU utilization.

A few observations:
- When switching tabs, e.g. to a smaller (i.e. few to no links) file, the CPU usage doesn't drop.
- When Zettlr is started with a _small_ file as the first tab being opened, everything is fine.
  - However, when the first tab upon start is a _large_ file (i.e. a lot of links), the CPU usage goes up, and stays up.
- When I start Zettlr with a small file, and keep switching tabs only between two small files, the CPU spike is not observed.
  - note that there still was a tab with the _large_ file; just never being switched to
- When closing the tab of the large file, the CPU usage doesn't drop

### Reproducing

1. Make sure to start Zettlr with a small file (e.g. empty)
2. Take note of Zettlr's idle CPU usage
3. Create/Open a new file with 500+ links (see https://github.com/Zettlr/Zettlr/issues/6057#issuecomment-3634149017)
4. After saving/opening, you should already see an increase in CPU usage by Zettlr
5. Try out my observations from above

### Zettlr version

v4.0.0-beta.4

### Installation Method

From the Website or GitHub

### Your Platform

- [x] Windows
- [ ] macOS
- [ ] Linux

### Architecture

- [x] Intel 64bit
- [ ] ARM 64bit (includes Apple Silicon)

### Operating System Version

Windows 11 Pro (10.0.26100 Build 26100

**Comment by nathanlesage** [comment]
Dies the CPU usage *deop* when you fully close that large file?

Based on what you explain, that might actually be caused by an issue in the Markdown parser that runs on the files in the main process.

**Comment by kyaso** [comment]
No, it does not drop when I close it.

However, I just noticed that my two large files have a _lot_ of ZKN links (>500). When I created a simple "lorem ipsum" file with ~20k words (only words, not links etc), Zettlr handles that perfectly fine, no CPU spike whatsoever!

**Comment by kyaso** [comment]
Ok, it seems that it is indeed linked (_pun intended_) to having many ZKN links. I can reproduce the issue simply by starting with an empty file, adding one link, and then copy-all-pasting, thus each time doubling the number of links. When I hit 256 links, and beyond, the CPU usage rises (and doesn't seem to drop after a reasonable time).

Also, there is no difference in behavior whether the links are placed on a single line or separated by new lines.

**Comment by benniekiss** [comment]
If you cause a hot-reload of the editor in a dev environment, do you notice the cpu usage going down? I'm also seeing a large cpu spike (>20% compared to typically ~6%)

**Comment by kyaso** [comment]
I tried hot-reloading, it didn't fix it, unfortunately.

**Comment by nathanlesage** [comment]
This might indicate that something in Main is borked. There is a parser running in main that is used to continuously update the link database for linking. Could be that I sprinkled a bit of a loop in there that wasn't supposed to be there ...?

Did this also occur on beta.3 or before?

**Comment by kyaso** [comment]
I did some quick testing, and found that the issue appears since beta.2; beta.1 is working fine.

**Comment by nathanlesage** [comment]
Okay, that already delimits it! Do you think you have time to do a `git bisect` to identify the exact commit when this started to occur? I recently found out that this is under-utilized for fixing those weird regression bugs …

**Comment by nathanlesage** [comment]
Just did a quick check and noticed that the beta.1->beta.2 update included my large FSAL refactor: https://github.com/Zettlr/Zettlr/commit/3bd234f8f521711e9e480ea9693496a125ce920d

I'm suspecting something in there broke.

**Comment by nathanlesage** [comment]
Continuing, I have a theory (although I couldn't prove it). In the changes to the LinkProvider, instituted in that refactor ([link](https://github.com/Zettlr/Zettlr/commit/3bd234f8f521711e9e480ea9693496a125ce920d#diff-1c7b137f9cef9e02d0bc8eaea7d015048e7efe2f94960ef64b260484e4799df2)), it will always rebuild the entire file index on any change. I have the suspicion that `fsal-event` is "any changed file".

Furthermore, since this only happens when a large file is open when the app is booted, and never happens when a small file is loaded when the app is booted, I presume a race condition that happens on start, but only if a file includes a large amount of internal links.

If anyone can dig a bit deeper, I'd appreciate this!

**Comment by nathanlesage** [comment]
It may be sufficient to implement a `lock` mechanism in the reindexing mechanism, so that it only runs once. (i.e., the fsal event just marks the state as "dirty" and decouples the indexing function from that.

**Comment by benniekiss** [comment]
I can't reproduce any sustained high cpu load, but I don't know how truthful the macos activity monitor is. 

@kyaso just to clarify, if you open the editor with a small file as the first tab, you do not get CPU spikes even when switching to the large file, or you DO get the CPU spike when switching, just not until you switch? 

Also, do you have the sidebar open by chance? One thing that may be causing it is the related files tab, since that queries the link database a lot, especially if you are clicking in and out of the editor pane: https://github.com/Zettlr/Zettlr/blob/0904e1cdab00ceecf7da622ff87cfc250fadf905/source/win-main/sidebar/RelatedFilesTab.vue#L123-L241

---

> it will always rebuild the entire file index on any change. I have the suspicion that `fsal-event` is "any changed file".

Do you mean [here](https://github.com/Zettlr/Zettlr/blob/0904e1cdab00ceecf7da622ff87cfc250fadf905/source/app/service-providers/links/index.ts#L61-L72)? If so, I tried putting some logging in, and it only triggers on things like file-save, rename, etc., not any change in text.

I haven't really noticed much in the code that would cause any sustained issue related to links, but there are two places I could see causing a slowdown that might want to be refactored --

The non-greedy regex in the following line could be a point of slowdown as it gets called in the fsal [`findExact`](https://github.com/Zettlr/Zettlr/blob/0904e1cdab00ceecf7da622ff87cfc250fadf905/source/app/service-providers/fsal/index.ts#L321) method, which is called on every file when [retrieving outbound links](https://github.com/Zettlr/Zettlr/blob/0904e1cdab00ceecf7da622ff87cfc250fadf905/source/app/service-providers/links/index.ts#L138)

https://github.com/Zettlr/Zettlr/blob/0904e1cdab00ceecf7da622ff87cfc250fadf905/source/common/regular-expressions.ts#L27

Otherwise, the only other slow point I found is the following test in the `retrieveInbound` method of fsal. With lots of links, this could slow down and points to the need for a `Set`.

https://github.com/Zettlr/Zettlr/blob/0904e1cdab00ceecf7da622ff87cfc250fadf905/source/app/service-providers/links/index.ts#L114

**Comment by kyaso** [comment]
> just to clarify, if you open the editor with a small file as the first tab, you do not get CPU spikes even when switching to the large file, or you DO get the CPU spike when switching, just not until you switch?

The latter, ie., as soon as I switch to the large file, the CPU usage spikes.

**Comment by nathanlesage** [comment]
Hm, maybe your hunch that the sidebar might be a culprit makes sense? Because the link retrieval only occurs on save etc., so any sustained CPU load might indicate that there is something going on *constantly* under the hood, and not just momentarily.

**Comment by benniekiss** [comment]
I recall other users were reporting performance issues in the sidebar as well, so it could be related to that -> #6018

**Comment by kyaso** [comment]
I noticed that the issue might also be linked to having a large workspace. If I start with a fresh workspace, and create a file with a lot of ZKN links, I don't see high sustained CPU usage. However, my personal workspace probably has well over 1000 files, and there, I can reproduce the issue.

**Comment by benniekiss** [comment]
I would definitely suspect the areas I highlighted above, then. Ill see whether I can reproduce with a large work space.

**Comment by kyaso** [comment]
I did some digging, and was (hopefully) able to narrow it down a bit.

If we below comment out the `recomputeRelatedFiles` in line 124, the high CPU usage does not appear anymore.
https://github.com/Zettlr/Zettlr/blob/18b1cf201cfb86f2a42c115333f235183ea437d1/source/win-main/sidebar/RelatedFilesTab.vue#L123-L129

**Comment by benniekiss** [comment]
The `recomputeRelatedFiles` has a lot of Array operations that I can definitely see slowing things down and causing CPU spikes.

**Comment by benniekiss** [comment]
@kyaso would you want to test out a branch of mine? I've been able to reproduce the high cpu usage, and I think i've addressed the cpu usage problem, but I'd appreciate if you'd check my patch before I submit a PR.  -> https://github.com/benniekiss/Zettlr/tree/links-perf

**Comment by kyaso** [comment]
@benniekiss Sure, thanks for quickly addressing this! I don't have time today and tomorrow, but will try it out on Saturday!

**Comment by benniekiss** [comment]
Somewhat related, but the citations tab also has some obvious performance issues that i'll be trying to address as well, and are likely piling onto the related files tab performance problems

**Comment by nathanlesage** [comment]
Please open separate PRs for both tabs -- the citation parser will need a refactor at some point in the near future, either way because I want to finally tap more into the capabilities of citeproc to improve the entire citation handling!

**Comment by kyaso** [comment]
@benniekiss I have tried your branch, and I was  still seeing the high CPU usage, unfortunately.

If the `recomputeRelatedFiles` method was not touched during the FSAL refactor (or was it?), I'm wondering what is causing that constant activity now; that same function is working fine in 3.6. 🤔



PS: I have no access to my dev machine for the next two weeks or so, so please expect some delays in my responses.

**Comment by benniekiss** [comment]
Looking through what changed in the link handling between then and now, it seems the only change really is the `findExact` method. That function was taken from the now-removed `workspace` provider and refactored into the `FSAL` provider. The logic also changed substantially. I haven't reviewed the old logic just yet, but the new implementation iterates over every descriptor, which would explain the high cpu usage when you have a lot of links and a lot of files open. It loops through every descriptor, and the function is called on every link. 

Here is the old code:

https://github.com/Zettlr/Zettlr/blob/5a4b76909e62cf2ebfa3579a2b2d524a8e33df0c/source/app/service-providers/workspaces/index.ts#L341-L374

Here is the current implementation:

https://github.com/Zettlr/Zettlr/blob/89bf4018525fbed9264b2851d8b106e84fc9a6ab/source/app/service-providers/fsal/index.ts#L315-L345

Here is where it is used in the `link` provider. The only substantive change between 3.6.0. and now is `this._workspaces.findExact`  to `this._fsal.findExact`:

https://github.com/Zettlr/Zettlr/blob/89bf4018525fbed9264b2851d8b106e84fc9a6ab/source/app/service-providers/links/index.ts#L122-L146

---

EDIT: So I did some testing by just logging the time of each segment, and the actual performance impact is in the `getAllLoadedDescriptors`. The rest of the code does not take long at all:

https://github.com/Zettlr/Zettlr/blob/89bf4018525fbed9264b2851d8b106e84fc9a6ab/source/app/service-providers/fsal/index.ts#L290-L313

---

EDIT 2: I haven't gotten much deeper into what specifically is slowing down the descriptor loading, and it may just be the large number of descriptors to load, but I believe #6041 will contribute to improving performance here, as well. 

Another thing that stood out to me is there are a lot of repeated filesystem calls, especially to `fs.access`, all down the call chain when loading a descriptor, and consolidating some of those repeated calls may also improve performance.

---

EDIT 3: So I've compiled a lot of changes here https://github.com/benniekiss/Zettlr/tree/sidebar-related-files . The biggest improvement comes from simply storing the output of `getAllLoadedDescriptors` after calling `reindex`. This prevents having to re-calculate `getAllLoadedDescriptors` every time `findExact` is called. I tested with my > 500 file folder, and I didn't notice any increased RAM usage. 

The other improvements in that branch also speed up the descriptor loading logic. I removed a lot of redundant `isDir` and `isFile` calls which speeds things up a lot.
