### ISSUE TITLE
Selecting the Italian Dictionary crashes the app | External Issue

### ISSUE THREAD

**Issue by mgiugliano** [Zettlr/Zettlr#80]
## Description
Execution stops and the program freezes (reproducibly).

## Reproducing
- launch it
- open preferences
- select the "Editor" tab
- add Italian dictionary
- press Save

## Expected behaviour
Zettlr should quit the preference panel and resume operation.

**Screenshots**

## Platform
 - OS: macOs Mojave 
 - OS Version: 10.14.1
 - Zettlr Version: 1.0
 - Screen Resolution [only necessary if the bug is relating to the GUI]

**Comment by nathanlesage** [comment]
I have now resorted to removing the Portugese and Italian dictionaries, so they won't ship with the app anymore. Besides making the app slimmer in shipped size, this way nobody who's not used to this problem won't run into accidentally crashing the app.

The problem runs deeper with all known node.js hunspell implementations, as none is able to cope with huge dictionaries at the moment. Smaller, thinner dictionaries of the languages affected will work, but not the "full version" of them, therefore I'll be discontinuing support for the time being. Let's hope the problems in both Typo.js and nspell, to which Zettlr will be switching, are resolved in due time. Until then, spellchecking will remain possible only for small datasets.

**Comment by enricllagostera** [comment]
Hi! Are there any news on this issue? I would really like to use Zettlr for Portuguese, but it continues to crash. Are there other spellchecking libraries that work better with Latin languages? It seems that the [nodehun library](https://github.com/Wulf/nodehun) has been having more active development than nspell. Would it be possible to test it out with Zettlr (I don't really have the expertise to do so)?

**Comment by nathanlesage** [comment]
Oh, I haven't noticed there has been development over there. But as nodehun requires native building of the respective modules, it will take some time.

If I don't react until June or so, feel free to open a new issue as a reminder!

**Comment by lucasaglimbeni** [comment]
I'm still experiencing this issue. I tried to use the italian dictionary from other apps using Hunspell (i.e. KitScenarist) yet still no fortune. I'm seriously looking forward to use Zettlr as my main and only writing app, but without a decent spell-check function I can only use it to forat and export PDF.
I love Zettlr, BTW

**Comment by nathanlesage** [comment]
@lucasaglimbeni Please see issue https://github.com/Zettlr/Zettlr/issues/1022
